REM
REM VERSION
REM FILENAME.vb
REM
REM Copyright DATUM INHABER
REM @GitHub JoergEm
REM
REM This program is WITHOUT ANY WARRANTY; without even the implied
REM warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
REM

START